import Foundation
import Testing
@testable import Ghostty

struct AgentSessionTests {
    // MARK: - SessionStatus

    @Test func sessionStatusHasThreeCases() {
        // Verify all three cases exist and are distinct.
        let running: SessionStatus = .running
        let exited: SessionStatus = .exited
        let killed: SessionStatus = .killed

        // Use if-case to confirm each case pattern-matches correctly.
        if case .running = running {} else { Issue.record("expected .running") }
        if case .exited = exited {} else { Issue.record("expected .exited") }
        if case .killed = killed {} else { Issue.record("expected .killed") }
    }

    // MARK: - AgentSession Init

    @Test func sessionInitStoresAllFields() {
        let templateId = SessionTemplate.shell.id
        let projectId = UUID()

        let session = AgentSession(
            name: "Shell — MyProject",
            templateId: templateId,
            projectId: projectId
        )

        #expect(session.name == "Shell — MyProject")
        #expect(session.templateId == templateId)
        #expect(session.projectId == projectId)
    }

    @Test func sessionIdIsAutoGenerated() {
        let session1 = AgentSession(name: "A", templateId: UUID(), projectId: UUID())
        let session2 = AgentSession(name: "B", templateId: UUID(), projectId: UUID())
        #expect(session1.id != session2.id)
    }

    // MARK: - Codable

    @Test func sessionCodableRoundTrip() throws {
        let original = AgentSession(
            name: "Claude Code — Test",
            templateId: SessionTemplate.claudeCode.id,
            projectId: UUID()
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.id == original.id)
        #expect(decoded.name == original.name)
        #expect(decoded.templateId == original.templateId)
        #expect(decoded.projectId == original.projectId)
    }

    // MARK: - Hashable

    @Test func sessionHashableUsesId() {
        let id = UUID()
        let projectId = UUID()
        let session1 = AgentSession(id: id, name: "A", templateId: UUID(), projectId: projectId)
        let session2 = AgentSession(id: id, name: "B", templateId: UUID(), projectId: projectId)
        // Same id means same hash, so a Set should deduplicate.
        let set: Set<AgentSession> = [session1, session2]
        #expect(set.count == 1)
    }
}
