import Foundation
import Testing
@testable import Ghostty

struct AgentSessionTests {
    // MARK: - SessionStatus

    @Test func sessionStatusHasAllCases() {
        // Verify all cases exist and are distinct.
        let running: SessionStatus = .running
        let exited: SessionStatus = .exited
        let completed: SessionStatus = .completed
        let error: SessionStatus = .error(exitCode: 1)
        let killed: SessionStatus = .killed

        // Use if-case to confirm each case pattern-matches correctly.
        if case .running = running {} else { Issue.record("expected .running") }
        if case .exited = exited {} else { Issue.record("expected .exited") }
        if case .completed = completed {} else { Issue.record("expected .completed") }
        if case .error = error {} else { Issue.record("expected .error") }
        if case .killed = killed {} else { Issue.record("expected .killed") }
    }

    @Test func sessionStatusIsAlive() {
        #expect(SessionStatus.running.isAlive == true)
        #expect(SessionStatus.exited.isAlive == false)
        #expect(SessionStatus.completed.isAlive == false)
        #expect(SessionStatus.error(exitCode: 1).isAlive == false)
        #expect(SessionStatus.killed.isAlive == false)
    }

    @Test func sessionStatusEquatable() {
        #expect(SessionStatus.running == .running)
        #expect(SessionStatus.error(exitCode: 1) == .error(exitCode: 1))
        #expect(SessionStatus.error(exitCode: 1) != .error(exitCode: 2))
        #expect(SessionStatus.completed != .exited)
    }

    // MARK: - SessionIndicatorState

    @Test func indicatorStatePriority() {
        // Error is highest priority, inactive is lowest.
        let states: [SessionIndicatorState] = [.inactive, .processing, .error, .waiting, .idle, .longRunning]
        let sorted = states.sorted()
        #expect(sorted == [.inactive, .idle, .processing, .longRunning, .waiting, .error])
    }

    // MARK: - AgentSession Init

    @Test func sessionInitStoresAllFields() {
        let templateId = AgentTemplate.shell.id
        let projectId = UUID()

        let session = AgentSession(
            name: "Shell — MyProject",
            templateId: templateId,
            projectId: projectId
        )

        #expect(session.name == "Shell — MyProject")
        #expect(session.templateId == templateId)
        #expect(session.projectId == projectId)
    }

    @Test func sessionIdIsAutoGenerated() {
        let session1 = AgentSession(name: "A", templateId: UUID(), projectId: UUID())
        let session2 = AgentSession(name: "B", templateId: UUID(), projectId: UUID())
        #expect(session1.id != session2.id)
    }

    // MARK: - Codable

    @Test func sessionCodableRoundTrip() throws {
        let original = AgentSession(
            name: "Claude Code — Test",
            templateId: AgentTemplate.claudeCode.id,
            projectId: UUID()
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.id == original.id)
        #expect(decoded.name == original.name)
        #expect(decoded.templateId == original.templateId)
        #expect(decoded.projectId == original.projectId)
    }

    // MARK: - Hashable

    @Test func sessionHashableUsesAllFields() {
        // AgentSession uses Swift's synthesized Hashable, which hashes ALL stored
        // properties — not just `id`. Two sessions with the same id but different
        // names or templateIds are treated as distinct values by Set/Dictionary.
        let id = UUID()
        let templateId = UUID()
        let projectId = UUID()

        // Identical fields → same hash → deduplicated.
        let session1 = AgentSession(id: id, name: "A", templateId: templateId, projectId: projectId)
        let session2 = AgentSession(id: id, name: "A", templateId: templateId, projectId: projectId)
        let deduped: Set<AgentSession> = [session1, session2]
        #expect(deduped.count == 1)

        // Different name → different hash → both kept.
        let session3 = AgentSession(id: id, name: "B", templateId: templateId, projectId: projectId)
        let distinct: Set<AgentSession> = [session1, session3]
        #expect(distinct.count == 2)
    }
}
