//! GLSL → SPIR-V → `VkShaderModule` pipeline.
//!
//! Approach: runtime compilation. The 10 GLSL sources in
//! `src/renderer/shaders/glsl/` are `@embedFile`'d and compiled via
//! the already-vendored `glslang` package (also used by
//! `shadertoy.zig` for custom user shaders). Compiled SPIR-V is fed
//! into `vkCreateShaderModule` to produce the handles that
//! `Pipeline.zig` will reference.
//!
//! Why not build-time compilation? It would be cleaner (no startup
//! cost, no glslang at runtime in the Vulkan binary) but requires
//! wiring glslang into `build.zig` as a build step, which is a
//! sizable detour. Runtime compilation reuses the existing glslang
//! integration verbatim. The startup cost is ~50ms total across all
//! shaders, acceptable for a terminal that starts rarely. Migrating
//! to build-time SPIR-V is a contained follow-up: swap the
//! `Module.init` call sites for `Module.initFromSpirv` of
//! `@embedFile`'d `.spv` blobs and delete the glslang import here.

const std = @import("std");
const builtin = @import("builtin");
const Allocator = std.mem.Allocator;
const vulkan = @import("vulkan");
const vk = vulkan.c;
const glslang = @import("glslang");

const Device = vulkan.Device;
const Sampler = vulkan.Sampler;
const DescriptorPool = vulkan.DescriptorPool;
const Pipeline = @import("Pipeline.zig");
const math = @import("../../math.zig");

/// Build-time-precompiled SPIR-V blobs for the 9 built-in
/// shaders. Generated by `src/build/VulkanSpv.zig`; each decl
/// is `[]const u8` from `@embedFile`. Bypasses runtime glslang
/// for built-ins, eliminating the TPoolAllocator high-water-
/// mark leak the per-process first-surface compile otherwise
/// leaves behind.
const vulkan_spv = @import("vulkan_spv");

/// Reinterpret a SPIR-V byte blob as the `[]const u32` word
/// slice `Module.initFromSpirv` expects. @embedFile gives us
/// `[]const u8` but SPIR-V is 4-byte-aligned words; the
/// alignCast is safe because @embedFile data is always at
/// least 4-byte-aligned and our .spv files are produced by
/// glslang which guarantees word-aligned output.
fn spvBytes(bytes: []const u8) []const u32 {
    const aligned: [*]align(@alignOf(u32)) const u8 = @alignCast(bytes.ptr);
    const words: [*]const u32 = @ptrCast(aligned);
    return words[0 .. bytes.len / @sizeOf(u32)];
}

const log = std.log.scoped(.vulkan);

/// Sources for the renderer's built-in shaders. Mirrors the table in
/// `opengl/shaders.zig`. Each entry is `@embedFile`'d so the binary
/// is self-contained.
///
/// Note: `common.glsl` is shared content `#include`'d by the others;
/// it is not a compilation unit and is not listed here. (The other
/// shaders are expected to splice it in via their existing
/// preprocessor pattern, the same way `opengl/shaders.zig` does.)
pub const source = struct {
    // Each source is the file with all `#include "..."` directives
    // expanded at comptime. glslang's preprocessor doesn't handle
    // GLSL includes without `GL_GOOGLE_include_directive`; rather
    // than enable that and provide a callback, we splice the
    // include contents inline — same approach `opengl/shaders.zig`
    // uses via its `loadShaderCode`.

    pub const bg_color_frag = processIncludes(@embedFile("../shaders/glsl/bg_color.f.glsl"));
    pub const bg_image_frag = processIncludes(@embedFile("../shaders/glsl/bg_image.f.glsl"));
    pub const bg_image_vert = processIncludes(@embedFile("../shaders/glsl/bg_image.v.glsl"));
    pub const cell_bg_frag = processIncludes(@embedFile("../shaders/glsl/cell_bg.f.glsl"));
    pub const cell_text_frag = processIncludes(@embedFile("../shaders/glsl/cell_text.f.glsl"));
    pub const cell_text_vert = processIncludes(@embedFile("../shaders/glsl/cell_text.v.glsl"));
    pub const full_screen_vert = processIncludes(@embedFile("../shaders/glsl/full_screen.v.glsl"));
    pub const image_frag = processIncludes(@embedFile("../shaders/glsl/image.f.glsl"));
    pub const image_vert = processIncludes(@embedFile("../shaders/glsl/image.v.glsl"));
};

/// Comptime `#include` preprocessor. Mirrors `opengl/shaders.zig`'s
/// `processIncludes` but specialized to the single `common.glsl`
/// include the renderer's shaders all use (so it doesn't need to
/// take a `basedir` parameter).
fn processIncludes(comptime contents: [:0]const u8) [:0]const u8 {
    @setEvalBranchQuota(100_000);
    var i: usize = 0;
    while (i < contents.len) {
        if (std.mem.startsWith(u8, contents[i..], "#include")) {
            // Skip whitespace (space or tab) between `#include` and
            // the opening quote. The previous literal-prefix
            // `startsWith("#include \"")` assert tripped on legal
            // `#include\t"…"` and `#include  "…"` variants. Accept
            // any horizontal whitespace and require exactly one
            // double-quoted path.
            var p = i + "#include".len;
            while (p < contents.len and (contents[p] == ' ' or contents[p] == '\t' or
                contents[p] == 0x0B or contents[p] == 0x0C)) : (p += 1)
            {}
            if (p >= contents.len or contents[p] != '"') {
                @compileError("processIncludes: malformed #include directive in shader");
            }
            const start = p + 1;
            const end = std.mem.indexOfScalarPos(u8, contents, start, '"') orelse
                @compileError("processIncludes: unterminated #include path");
            return std.fmt.comptimePrint("{s}{s}{s}", .{
                contents[0..i],
                @embedFile("../shaders/glsl/" ++ contents[start..end]),
                processIncludes(contents[end + 1 ..]),
            });
        }
        if (std.mem.indexOfPos(u8, contents, i, "\n#")) |j| {
            i = (j + 1);
        } else {
            break;
        }
    }
    return contents;
}

pub const Stage = enum {
    vertex,
    fragment,

    /// Map to the binding-layer enum that `glslang.vk.compileToSpv`
    /// accepts. Same shape, different module — keeping the enum at
    /// this level so the renderer's `.vertex` / `.fragment` literals
    /// stay backend-flavored (the `vk_*` field on the struct also
    /// reads off this enum).
    pub fn vkBindingStage(self: Stage) glslang.vk.Stage {
        return switch (self) {
            .vertex => .vertex,
            .fragment => .fragment,
        };
    }

    fn vkStage(self: Stage) vk.VkShaderStageFlagBits {
        return switch (self) {
            .vertex => vk.VK_SHADER_STAGE_VERTEX_BIT,
            .fragment => vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        };
    }
};

pub const Error = error{
    /// `glslang_shader_preprocess` / `_parse` / `_program_link` /
    /// `_program_SPIRV_generate` failed. Detailed errors are logged
    /// via `std.log.err` with the glslang info / debug strings.
    GlslangFailed,
    /// `vkCreateShaderModule` returned a non-success status.
    VulkanFailed,
} || std.mem.Allocator.Error;

/// Resource type, used to assign disjoint descriptor sets when
/// rewriting GLSL `layout(...)` declarations for Vulkan. The shaders
/// were authored against OpenGL where each resource type has its own
/// binding space; Vulkan shares a single binding namespace within a
/// descriptor set. We bucket each resource type into its own set so
/// the original OpenGL binding numbers don't collide.
const ResourceSet = enum(u8) {
    /// Uniform blocks. `Globals` (binding=1) goes here.
    ubo = 0,
    /// Combined image samplers (`sampler2D`, `sampler2DRect`-was, ...).
    sampler = 1,
    /// SSBOs (`readonly buffer`, `buffer`). `bg_cells` (binding=1) goes here.
    storage = 2,
};

/// Translate OpenGL-flavored GLSL to its Vulkan equivalent in the
/// places glslang doesn't auto-translate:
///
///   1. `gl_VertexID`   → `gl_VertexIndex`
///   2. `gl_InstanceID` → `gl_InstanceIndex`
///   3. `sampler2DRect` → `sampler2D` (Vulkan 1.3 doesn't allow the
///      `SampledRect` SPIR-V capability; the sampler-side workaround
///      is `unnormalizedCoordinates = VK_TRUE` so the shader's
///      texture()/texelFetch() pixel-coord math keeps working).
///   4. `layout(binding = N, ...) <decl>` →
///      `layout(set = S, binding = N, ...) <decl>`, where S is the
///      descriptor set for the resource type of `<decl>`:
///        - UBO blocks            → set 0
///        - sampler-family decls  → set 1
///        - storage buffers       → set 2
///      Other `layout(...)` qualifiers (e.g. `location = 0`) are
///      passed through unchanged.
///
/// glslang's `setEnvInput(EShClientVulkan)` handles a lot but not
/// these source-level renames or the descriptor-set assignment —
/// `setAutoMapBindings(true)` only remaps *unbound* resources, and
/// our shaders all use explicit `binding = N` from their OpenGL
/// authoring.
///
/// Caller frees the returned buffer with the same allocator.
///
/// Also called from `shadertoy.zig` when building SPIR-V for the
/// Vulkan backend's custom-shader path, so the binding layouts in the
/// user's shader come out in the same set/binding scheme the
/// renderer's pipelines wire up.
pub fn vulkanizeGlsl(
    alloc: std.mem.Allocator,
    src: []const u8,
) std.mem.Allocator.Error![:0]const u8 {
    // First pass: identifier-level rewrites (renames + sampler2DRect)
    // plus `texture(` → `textureLod(...,0.0)`. The `texture()` rewrite
    // is needed because Vulkan forbids the SPIR-V OpImageSampleImplicitLod
    // opcode (what `texture()` compiles to) when the sampler has
    // `unnormalizedCoordinates = VK_TRUE` — which our cell_text atlas
    // sampler does so its pixel-coord math (inherited from
    // `sampler2DRect`) keeps working. `textureLod(s, uv, 0.0)`
    // compiles to OpImageSampleExplicitLod, which IS allowed with
    // unnormalized samplers and reads the same texel at LOD 0 for our
    // non-mipmapped atlases.
    const pass1 = pass1: {
        var out = std.ArrayList(u8){};
        errdefer out.deinit(alloc);

        var i: usize = 0;
        while (i < src.len) {
            // Skip comments + string literals verbatim — anything
            // that looks like an identifier inside one of those is
            // not a real token, and rewriting it (e.g. a comment
            // that mentions `gl_VertexID` or `texture(atlas_*, ...)`)
            // would silently corrupt the shader source.
            if (try copySkippable(alloc, &out, src, &i)) continue;
            const c = src[i];
            const is_ident_start = isIdentChar(c);
            if (is_ident_start) {
                const start = i;
                while (i < src.len and isIdentChar(src[i])) : (i += 1) {}
                const ident = src[start..i];
                // Special-case `texture` followed by `(`: rewrite to
                // `textureLod(...,0.0)`. Other identifiers starting
                // with "texture" (e.g. `texture2D` if we ever see it,
                // or local variable names) are NOT rewritten because
                // the check requires the next non-space char to be
                // exactly `(` AND the rewrite injects an extra
                // argument before the matching `)`.
                if (std.mem.eql(u8, ident, "gl_VertexID")) {
                    try out.appendSlice(alloc, "gl_VertexIndex");
                } else if (std.mem.eql(u8, ident, "gl_InstanceID")) {
                    try out.appendSlice(alloc, "gl_InstanceIndex");
                } else if (std.mem.eql(u8, ident, "sampler2DRect")) {
                    try out.appendSlice(alloc, "sampler2D");
                } else if (std.mem.eql(u8, ident, "texture") and
                    nextSamplerIsUnnormalized(src, i))
                {
                    // Replace `texture(args)` with `textureLod(args, 0.0)`
                    // ONLY when the sampler argument is one we created
                    // with `unnormalized_coordinates = true` (the atlas
                    // samplers in cell_text.f). Vulkan forbids implicit-LOD
                    // sampling for those — see VUID-vkCmdDraw-None-08610.
                    // For every other sampler (cell_bg.f's storage, the
                    // shadertoy `iChannel0`, etc.) leave `texture()` alone:
                    // it's the faster opcode the driver wants for normal
                    // mipmapped or LOD-derivative sampling.
                    try out.appendSlice(alloc, "textureLod(");
                    // Skip whitespace AND comments AND string literals
                    // between the identifier and the opening `(`.
                    // `copySkippable` consumes any of those into `out`
                    // verbatim if present; a literal `(` inside a
                    // `/* */` block comment must NOT be mistaken for
                    // the call paren. Plain `src[i] != '('` (the
                    // earlier form) wasn't comment-aware.
                    while (i < src.len) {
                        if (try copySkippable(alloc, &out, src, &i)) continue;
                        if (src[i] == '(') break;
                        // Anything else between the identifier and `(`
                        // is a syntax error in valid GLSL; copy it
                        // through and let glslang reject downstream.
                        try out.append(alloc, src[i]);
                        i += 1;
                    }
                    if (i >= src.len) break; // unterminated; bail
                    i += 1; // consume the '('
                    var depth: i32 = 1;
                    while (i < src.len and depth > 0) {
                        // Skip comments and string literals verbatim
                        // — a `(` or `)` inside `/* */` or `"..."`
                        // shouldn't move our paren depth tracker.
                        if (try copySkippable(alloc, &out, src, &i)) continue;
                        const cc = src[i];
                        if (cc == '(') depth += 1;
                        if (cc == ')') {
                            depth -= 1;
                            if (depth == 0) break;
                        }
                        try out.append(alloc, cc);
                        i += 1;
                    }
                    try out.appendSlice(alloc, ", 0.0)");
                    if (i < src.len) i += 1; // consume the closing `)`
                } else {
                    try out.appendSlice(alloc, ident);
                }
            } else {
                try out.append(alloc, c);
                i += 1;
            }
        }
        break :pass1 try out.toOwnedSlice(alloc);
    };
    defer alloc.free(pass1);

    // Second pass: layout(...) qualifier rewrites. We need the rect→2D
    // rename from pass 1 to have already happened so that the
    // resource-type sniff sees `sampler2D` rather than `sampler2DRect`.
    var out = std.ArrayList(u8){};
    errdefer out.deinit(alloc);

    var i: usize = 0;
    while (i < pass1.len) {
        // Skip comments + string literals verbatim, same reason as
        // pass 1 — rewriting `layout(binding=…)` text inside a
        // comment would inject a `set =` qualifier into a comment
        // that's never compiled, harmless today but a footgun.
        if (try copySkippable(alloc, &out, pass1, &i)) continue;
        if (matchKeyword(pass1, i, "layout")) |layout_end| {
            // Skip whitespace between `layout` and `(`.
            var p = layout_end;
            while (p < pass1.len and isHorizSpace(pass1[p])) p += 1;
            if (p >= pass1.len or pass1[p] != '(') {
                try out.appendSlice(alloc, pass1[i..p]);
                i = p;
                continue;
            }
            // Find the matching ')'. layout() never nests parens in
            // these shaders, but track depth defensively. Skip
            // comments and string literals so a `)` inside a
            // `/* */` block doesn't close the body prematurely
            // (consistency with the pass-1 texture rewriter which
            // already does this).
            const body_start = p + 1;
            var body_end = body_start;
            var depth: i32 = 1;
            while (body_end < pass1.len and depth > 0) {
                // Note: we DON'T copy skipped tokens to `out` here —
                // the layout body is replaced wholesale once we know
                // the resource type, so we just need to walk past it.
                // Inline the skip logic since `copySkippable` writes
                // into the output buffer.
                if (skipPast(pass1, &body_end)) continue;
                switch (pass1[body_end]) {
                    '(' => depth += 1,
                    ')' => depth -= 1,
                    else => {},
                }
                body_end += 1;
            }
            // body_end now points one past the closing ')'. The body
            // itself is pass1[body_start .. body_end - 1].
            if (depth != 0) {
                // Unbalanced — bail and emit the rest verbatim.
                try out.appendSlice(alloc, pass1[i..]);
                i = pass1.len;
                continue;
            }
            const body = pass1[body_start .. body_end - 1];
            const has_binding = containsKeyword(body, "binding");
            const has_set_already = containsKeyword(body, "set");
            if (!has_binding or has_set_already) {
                // Either no `binding =` (e.g. `layout(location = 0)`),
                // or someone already specified `set = N` — pass through.
                try out.appendSlice(alloc, pass1[i..body_end]);
                i = body_end;
                continue;
            }
            // Look past the ')' for the resource type.
            const set = detectResourceSet(pass1, body_end) orelse {
                try out.appendSlice(alloc, pass1[i..body_end]);
                i = body_end;
                continue;
            };

            // Emit: `layout(set = <S>, <body>)`.
            try out.appendSlice(alloc, "layout(set = ");
            try out.writer(alloc).print("{d}", .{@intFromEnum(set)});
            try out.appendSlice(alloc, ", ");
            try out.appendSlice(alloc, body);
            try out.append(alloc, ')');
            i = body_end;
        } else {
            try out.append(alloc, pass1[i]);
            i += 1;
        }
    }

    return try out.toOwnedSliceSentinel(alloc, 0);
}

/// If position `i` in `src` is the start of a GLSL line comment
/// (`//...\n`), block comment (`/* ... */`), or `"..."` string
/// literal, copy the whole token verbatim into `out`, advance
/// `*i` past it, and return true. Otherwise `*i` is unchanged
/// and we return false.
///
/// Strings are unusual in GLSL but `#extension` directives can
/// quote in some preprocessor flavors, and the safe thing is to
/// leave any quoted run untouched.
fn copySkippable(
    alloc: std.mem.Allocator,
    out: *std.ArrayList(u8),
    src: []const u8,
    i: *usize,
) std.mem.Allocator.Error!bool {
    const start = i.*;
    if (start >= src.len) return false;
    if (start + 1 < src.len and src[start] == '/' and src[start + 1] == '/') {
        var p = start;
        while (p < src.len and src[p] != '\n') : (p += 1) {}
        try out.appendSlice(alloc, src[start..p]);
        i.* = p;
        return true;
    }
    if (start + 1 < src.len and src[start] == '/' and src[start + 1] == '*') {
        var p = start + 2;
        while (p + 1 < src.len and !(src[p] == '*' and src[p + 1] == '/')) : (p += 1) {}
        // Include the closing `*/` if found; otherwise consume to EOF.
        const end = if (p + 1 < src.len) p + 2 else src.len;
        try out.appendSlice(alloc, src[start..end]);
        i.* = end;
        return true;
    }
    if (src[start] == '"') {
        var p = start + 1;
        while (p < src.len and src[p] != '"') : (p += 1) {
            if (src[p] == '\\' and p + 1 < src.len) p += 1;
        }
        const end = if (p < src.len) p + 1 else src.len;
        try out.appendSlice(alloc, src[start..end]);
        i.* = end;
        return true;
    }
    return false;
}

/// Walk-past variant of `copySkippable` for callers that don't want
/// to copy the skipped run anywhere — they're scanning, not
/// rewriting. Same recognition rules: line comment, block comment,
/// string literal. Returns true if `*i` advanced.
fn skipPast(src: []const u8, i: *usize) bool {
    const start = i.*;
    if (start >= src.len) return false;
    if (start + 1 < src.len and src[start] == '/' and src[start + 1] == '/') {
        var p = start;
        while (p < src.len and src[p] != '\n') : (p += 1) {}
        i.* = p;
        return true;
    }
    if (start + 1 < src.len and src[start] == '/' and src[start + 1] == '*') {
        var p = start + 2;
        while (p + 1 < src.len and !(src[p] == '*' and src[p + 1] == '/')) : (p += 1) {}
        i.* = if (p + 1 < src.len) p + 2 else src.len;
        return true;
    }
    if (src[start] == '"') {
        var p = start + 1;
        while (p < src.len and src[p] != '"') : (p += 1) {
            if (src[p] == '\\' and p + 1 < src.len) p += 1;
        }
        i.* = if (p < src.len) p + 1 else src.len;
        return true;
    }
    return false;
}

fn isIdentChar(c: u8) bool {
    return (c >= 'a' and c <= 'z') or
        (c >= 'A' and c <= 'Z') or
        (c >= '0' and c <= '9') or
        c == '_';
}

/// Names of samplers we create with `unnormalized_coordinates =
/// VK_TRUE`. The shaders here all use only the two atlas samplers
/// for cell_text; if more get added (or renamed) update this list.
/// The fragment shader `cell_text.f.glsl` is the only renderer
/// shader that references either name, so this list is intentionally
/// tiny — broader matching would force `textureLod` on the custom
/// shader's `iChannel0`, which is normalized, and bypassing the
/// implicit-LOD opcode path makes the driver work harder per call.
///
/// User-supplied custom shaders MUST NOT name a sampler `atlas_grayscale`
/// or `atlas_color` — doing so will trigger this rewrite and replace
/// `texture()` calls on that sampler with `textureLod(..., 0.0)`,
/// which is incorrect for any normalized sampler. The shadertoy
/// shader convention uses `iChannel0..3`, so the conflict is unlikely
/// in practice.
const unnormalized_sampler_names = [_][]const u8{
    "atlas_grayscale",
    "atlas_color",
};

/// True when `texture(IDENT, ...)` at position `i` (positioned right
/// after the `texture` identifier) names an unnormalized sampler.
/// Walks past whitespace and the `(`, then reads the next identifier
/// and matches it against `unnormalized_sampler_names`.
fn nextSamplerIsUnnormalized(src: []const u8, i: usize) bool {
    var p = i;
    while (p < src.len and isAnySpace(src[p])) : (p += 1) {}
    if (p >= src.len or src[p] != '(') return false;
    p += 1;
    while (p < src.len and isAnySpace(src[p])) : (p += 1) {}
    if (p >= src.len or !isIdentChar(src[p])) return false;
    const start = p;
    while (p < src.len and isIdentChar(src[p])) : (p += 1) {}
    const name = src[start..p];
    for (unnormalized_sampler_names) |needle| {
        if (std.mem.eql(u8, name, needle)) return true;
    }
    return false;
}

fn isHorizSpace(c: u8) bool {
    // GLSL preprocessor whitespace per the spec: space, tab,
    // vertical tab, form feed. Newline + carriage return are
    // separately handled as line terminators.
    return c == ' ' or c == '\t' or c == 0x0B or c == 0x0C;
}

fn isAnySpace(c: u8) bool {
    return c == ' ' or c == '\t' or c == '\n' or c == '\r';
}

/// Match `keyword` as a whole-word token starting at `i`. Returns
/// the offset one past the end of the match, or null if no match.
/// Whole-word means the character before `i` (if any) and the
/// character after the match must NOT be identifier-continuation
/// characters.
fn matchKeyword(src: []const u8, i: usize, keyword: []const u8) ?usize {
    if (i + keyword.len > src.len) return null;
    if (!std.mem.eql(u8, src[i .. i + keyword.len], keyword)) return null;
    if (i > 0 and isIdentChar(src[i - 1])) return null;
    const end = i + keyword.len;
    if (end < src.len and isIdentChar(src[end])) return null;
    return end;
}

/// Whole-word containment check for substring search inside a
/// `layout(...)` body.
fn containsKeyword(body: []const u8, keyword: []const u8) bool {
    var i: usize = 0;
    while (i < body.len) : (i += 1) {
        if (matchKeyword(body, i, keyword) != null) return true;
    }
    return false;
}

/// Look past the `)` that closed a `layout(...)` qualifier to figure
/// out what kind of resource the declaration introduces. Returns
/// null if it isn't a descriptor-bound resource (e.g. an `in` /
/// `out` varying that incidentally had `binding =` — none of our
/// shaders do this, but be defensive).
fn detectResourceSet(src: []const u8, after_close_paren: usize) ?ResourceSet {
    var i = after_close_paren;
    while (i < src.len and isAnySpace(src[i])) : (i += 1) {}
    if (i >= src.len) return null;
    if (!isIdentChar(src[i])) return null;
    const tok1_start = i;
    while (i < src.len and isIdentChar(src[i])) : (i += 1) {}
    const tok1 = src[tok1_start..i];

    // Storage buffers: `readonly buffer NAME { ... };` or
    // `buffer NAME { ... };`. The `readonly` qualifier is optional
    // but always present in our shaders.
    if (std.mem.eql(u8, tok1, "buffer")) return .storage;
    if (std.mem.eql(u8, tok1, "readonly")) return .storage;
    if (std.mem.eql(u8, tok1, "writeonly")) return .storage;
    if (std.mem.eql(u8, tok1, "coherent")) return .storage;

    // `uniform <something>`: distinguish sampler-family from UBO block.
    if (!std.mem.eql(u8, tok1, "uniform")) return null;

    while (i < src.len and isAnySpace(src[i])) : (i += 1) {}
    if (i >= src.len or !isIdentChar(src[i])) return null;
    const tok2_start = i;
    while (i < src.len and isIdentChar(src[i])) : (i += 1) {}
    const tok2 = src[tok2_start..i];

    // Sampler family: `sampler*`, `texture*`, `image*`.
    if (std.mem.startsWith(u8, tok2, "sampler")) return .sampler;
    if (std.mem.startsWith(u8, tok2, "texture")) return .sampler;
    if (std.mem.startsWith(u8, tok2, "image")) return .sampler;

    // Otherwise treat it as a UBO block.
    return .ubo;
}

/// A compiled `VkShaderModule` plus its stage flag.
pub const Module = struct {
    handle: vk.VkShaderModule,
    stage: vk.VkShaderStageFlagBits,
    device: *const Device,

    /// Compile GLSL → SPIR-V → `VkShaderModule` in a single pass.
    ///
    /// The source is run through `vulkanizeGlsl` to swap OpenGL-only
    /// builtins for their Vulkan equivalents (`gl_VertexID` →
    /// `gl_VertexIndex`, `gl_InstanceID` → `gl_InstanceIndex`); then
    /// `glslang.vk.compileToSpv` (typed wrapper around the Vulkan
    /// compile shim in `pkg/glslang/override/ghastty_vk_shim.cpp`)
    /// finishes the job with auto-map bindings / locations enabled.
    /// Same path covers the renderer's built-in shaders AND
    /// user-supplied custom shaders, so the OpenGL-flavored GLSL
    /// Ghostty already speaks keeps working.
    pub fn init(
        alloc: std.mem.Allocator,
        device: *const Device,
        src: [:0]const u8,
        stage: Stage,
    ) Error!Module {
        // Mirror shadertoy.zig — tests don't call `glslang.init`
        // themselves.
        if (builtin.is_test) glslang.testing.ensureInit() catch {
            return error.GlslangFailed;
        };

        // vulkanizeGlsl returns `Allocator.Error` only — surface it
        // via `try` (Module.Error includes Allocator.Error) so OOM
        // doesn't get reported as `error.GlslangFailed`. Conflating
        // them masked the actual failure mode in earlier diagnostics.
        const translated = try vulkanizeGlsl(alloc, src);
        defer alloc.free(translated);

        const spv = try glslang.vk.compileToSpv(alloc, translated, stage.vkBindingStage());
        defer alloc.free(spv);
        return try initFromSpirv(device, spv, stage);
    }

    /// Wrap pre-compiled SPIR-V as a `VkShaderModule`. Useful for the
    /// eventual build-time-blob path, and as the lower half of `init`.
    pub fn initFromSpirv(
        device: *const Device,
        spirv: []const u32,
        stage: Stage,
    ) Error!Module {
        // Sanity-check the SPIR-V before handing it to the driver.
        // The glslang and shadertoy paths both validate already, but
        // a future caller wiring up the build-time-blob path could
        // accidentally pass an empty or non-SPIR-V buffer; failing
        // here with a clear error beats a `vkCreateShaderModule`
        // segfault inside the loader.
        if (spirv.len == 0) {
            log.err("Module.initFromSpirv: zero-length SPIR-V buffer", .{});
            return error.VulkanFailed;
        }
        if (spirv[0] != 0x07230203) {
            log.err(
                "Module.initFromSpirv: missing magic word " ++
                    "(got 0x{x:0>8}, expected 0x07230203)",
                .{spirv[0]},
            );
            return error.VulkanFailed;
        }
        const info: vk.VkShaderModuleCreateInfo = .{
            .sType = vk.VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
            .pNext = null,
            .flags = 0,
            .codeSize = spirv.len * @sizeOf(u32),
            .pCode = spirv.ptr,
        };
        var handle: vk.VkShaderModule = undefined;
        const r = device.dispatch.createShaderModule(
            device.device,
            &info,
            null,
            &handle,
        );
        if (r != vk.VK_SUCCESS) {
            log.err("vkCreateShaderModule failed: result={}", .{r});
            return error.VulkanFailed;
        }
        return .{
            .handle = handle,
            .stage = stage.vkStage(),
            .device = device,
        };
    }

    pub fn deinit(self: Module) void {
        self.device.dispatch.destroyShaderModule(
            self.device.device,
            self.handle,
            null,
        );
    }
};

// ---- shader data types ----------------------------------------------
//
// These mirror the same-named declarations in `opengl/shaders.zig`
// and `metal/shaders.zig`. The structs describe memory layouts the
// GLSL source consumes verbatim — same shader sources are compiled
// for every backend, so the struct layouts must agree.

pub const Uniforms = extern struct {
    projection_matrix: math.Mat align(16),
    screen_size: [2]f32 align(8),
    cell_size: [2]f32 align(8),
    grid_size: [2]u16 align(4),
    grid_padding: [4]f32 align(16),
    padding_extend: PaddingExtend align(4),
    min_contrast: f32 align(4),
    cursor_pos: [2]u16 align(4),
    cursor_color: [4]u8 align(4),
    bg_color: [4]u8 align(4),
    bools: Bools align(4),

    pub const Bools = packed struct(u32) {
        cursor_wide: bool,
        use_display_p3: bool,
        use_linear_blending: bool,
        use_linear_correction: bool = false,
        _padding: u28 = 0,
    };

    pub const PaddingExtend = packed struct(u32) {
        left: bool = false,
        right: bool = false,
        up: bool = false,
        down: bool = false,
        _padding: u28 = 0,
    };
};

pub const CellText = extern struct {
    glyph_pos: [2]u32 align(8) = .{ 0, 0 },
    glyph_size: [2]u32 align(8) = .{ 0, 0 },
    bearings: [2]i16 align(4) = .{ 0, 0 },
    grid_pos: [2]u16 align(4),
    color: [4]u8 align(4),
    atlas: Atlas align(1),
    bools: packed struct(u8) {
        no_min_contrast: bool = false,
        is_cursor_glyph: bool = false,
        _padding: u6 = 0,
    } align(1) = .{},

    pub const Atlas = enum(u8) {
        grayscale = 0,
        color = 1,
    };
};

pub const CellBg = [4]u8;

pub const Image = extern struct {
    grid_pos: [2]f32 align(8),
    cell_offset: [2]f32 align(8),
    source_rect: [4]f32 align(16),
    dest_size: [2]f32 align(8),
};

pub const BgImage = extern struct {
    opacity: f32 align(4),
    info: Info align(1),

    pub const Info = packed struct(u8) {
        position: Position,
        fit: Fit,
        repeat: bool,
        _padding: u1 = 0,

        pub const Position = enum(u4) {
            tl = 0,
            tc = 1,
            tr = 2,
            ml = 3,
            mc = 4,
            mr = 5,
            bl = 6,
            bc = 7,
            br = 8,
        };

        pub const Fit = enum(u2) {
            contain = 0,
            cover = 1,
            stretch = 2,
            none = 3,
        };
    };
};

// ---- Shaders collection ---------------------------------------------

/// Pipeline collection shape (matches `opengl/shaders.zig`). Each
/// field is the Vulkan `Pipeline` instance for that named shader.
///
/// Default-init to all-null handles: pipelines that haven't been
/// constructed yet have `pipeline == null`, which `RenderPass.step`
/// detects and silently skips. Using `Pipeline = undefined` instead
/// would leak Debug-mode 0xAA poison bytes into VkPipeline / VkDevice
/// handles, which validation rightly flags as invalid.
pub const PipelineCollection = struct {
    bg_color: Pipeline = empty_pipeline,
    cell_bg: Pipeline = empty_pipeline,
    cell_text: Pipeline = empty_pipeline,
    image: Pipeline = empty_pipeline,
    bg_image: Pipeline = empty_pipeline,
};

const empty_pipeline: Pipeline = .{
    .device = undefined, // unused — gated behind pipeline-handle null checks
    .pipeline = null,
    .layout = null,
};

/// Top-level renderer shader state. Same shape as
/// `opengl/shaders.zig`'s `Shaders` so the generic renderer's call
/// sites work without per-backend branching.
///
/// `Shaders.init`:
///   - Compiles all 9 built-in GLSL sources via `Module.init` (the
///     glslang shim — same code path user shaders go through).
///   - Creates per-pipeline descriptor set layouts + a single
///     descriptor pool sized for the static pipeline set.
///   - Builds one `Pipeline` per renderer shader (`bg_color`,
///     `cell_bg`, `cell_text`, `image`, `bg_image`) plus one per
///     user-supplied post-shader.
/// `Shaders.deinit` walks the same set in reverse to destroy
/// pipelines, layouts, samplers, the descriptor pool, and modules.
pub const Shaders = struct {
    /// Borrowed pointer to the host-owned VkDevice wrapper. Stored
    /// so `deinit` can reach the device dispatch table without
    /// reaching into an arbitrary module's `.device` field (which
    /// would silently break if `Modules` is restructured). The
    /// pointer outlives `Shaders` because the device is process-
    /// global in `Vulkan.zig`.
    device: *const Device,
    pipelines: PipelineCollection,
    /// One per user-supplied custom shader. Built by `Shaders.init`
    /// from the `post_shaders` arg — empty when no custom shaders.
    /// Owned by `Shaders` (deinit destroys each + frees the slice
    /// using the allocator passed to `deinit`).
    post_pipelines: []Pipeline,
    /// Compiled `VkShaderModule`s for each user shader, parallel to
    /// `post_pipelines`. Owned by `Shaders` (deinit destroys each).
    post_modules: []Module = &.{},
    modules: Modules,

    /// Process-wide descriptor pool. Sized for one set per pipeline
    /// at startup; `RenderPass.step` updates the sets in place each
    /// frame (we wait on the fence in `Frame.complete`, so reuse is
    /// safe — no command buffer using these sets is in flight when
    /// the next frame begins).
    descriptor_pool: ?DescriptorPool = null,

    /// Descriptor set layouts created by `init`, kept alive for the
    /// lifetime of `Shaders` and destroyed in `deinit`. Each pipeline
    /// holds raw `VkDescriptorSetLayout` handles into this array —
    /// `Shaders` owns the lifetime so individual pipelines don't have
    /// to. Fixed-size because the pipeline set is small and known.
    set_layouts: [16]vk.VkDescriptorSetLayout = [_]vk.VkDescriptorSetLayout{null} ** 16,
    set_layouts_len: usize = 0,

    /// 0-binding placeholder descriptor set layout. Vulkan requires
    /// `pSetLayouts[i]` in the pipeline layout to be non-null for
    /// every set up to the max used. When a pipeline uses sets 0 and
    /// 2 but not 1, we substitute this layout for the set-1 slot.
    /// Also tracked in `set_layouts` for deinit.
    empty_set_layout: vk.VkDescriptorSetLayout = null,

    /// Sampler used by the cell_text pipeline for both atlas
    /// textures. Unnormalized coordinates so `texture(s, pixel_xy)`
    /// keeps the OpenGL `sampler2DRect` semantics the shaders were
    /// authored against. Owned by `Shaders` and destroyed in
    /// `deinit`.
    atlas_sampler: ?Sampler = null,

    /// Sampler used by the image + bg_image pipelines. Normalized
    /// linear sampling, clamp-to-edge — the standard 2D mode.
    image_sampler: ?Sampler = null,

    defunct: bool = false,

    /// The compiled `VkShaderModule`s for the renderer's built-in
    /// shaders. One entry per source file. Held by `Shaders` so the
    /// (eventual) per-pipeline `Pipeline.init` can reference them
    /// without re-compiling on every assemble.
    pub const Modules = struct {
        bg_color_frag: Module,
        bg_image_frag: Module,
        bg_image_vert: Module,
        cell_bg_frag: Module,
        cell_text_frag: Module,
        cell_text_vert: Module,
        full_screen_vert: Module,
        image_frag: Module,
        image_vert: Module,
    };

    pub fn init(
        alloc: Allocator,
        device: *const Device,
        // SPIR-V binaries (4-byte-aligned) from
        // `shadertoy.loadFromFiles` with `target = .spv`. The Vulkan
        // backend bypasses the spirv-cross GLSL roundtrip the other
        // backends use, so each entry here is the SPIR-V the
        // built-in glslang shim would have produced.
        post_shaders: []const []const u8,
    ) !Shaders {
        // Compile each built-in shader. Errors are fatal — the
        // renderer can't run without these. The `errdefer` chain
        // tears down any successfully-compiled modules if a later
        // one fails so we don't leak `VkShaderModule` handles on
        // partial failure.
        //
        // All 9 modules compile now that `vulkanizeGlsl` rewrites
        // OpenGL-only constructs (`sampler2DRect` → `sampler2D` and
        // disjoint descriptor sets per resource type). Pipelines are
        // built incrementally as the per-pipeline descriptor layouts
        // get wired up; today only bg_color has its pipeline. The
        // unused pipeline slots stay null-handle sentinels and
        // `RenderPass.step` skips them.
        // Use the SPIR-V blobs precompiled at build time by
        // src/build/VulkanSpv.zig — skips the glslang call path
        // for built-ins, which is what was leaking ~10 MB of
        // TPoolAllocator pages per process on first surface init.
        // Custom (user) shaders still go through glslang at
        // runtime via shadertoy.spirvFromGlsl, and the per-frame
        // shadertoy post-pipeline below still allocates via
        // `alloc`, so the parameter is still load-bearing.
        var modules: Modules = .{
            .bg_color_frag = try Module.initFromSpirv(device, spvBytes(vulkan_spv.bg_color_frag), .fragment),
            .bg_image_frag = try Module.initFromSpirv(device, spvBytes(vulkan_spv.bg_image_frag), .fragment),
            .bg_image_vert = try Module.initFromSpirv(device, spvBytes(vulkan_spv.bg_image_vert), .vertex),
            .cell_bg_frag = try Module.initFromSpirv(device, spvBytes(vulkan_spv.cell_bg_frag), .fragment),
            .cell_text_frag = try Module.initFromSpirv(device, spvBytes(vulkan_spv.cell_text_frag), .fragment),
            .cell_text_vert = try Module.initFromSpirv(device, spvBytes(vulkan_spv.cell_text_vert), .vertex),
            .full_screen_vert = try Module.initFromSpirv(device, spvBytes(vulkan_spv.full_screen_vert), .vertex),
            .image_frag = try Module.initFromSpirv(device, spvBytes(vulkan_spv.image_frag), .fragment),
            .image_vert = try Module.initFromSpirv(device, spvBytes(vulkan_spv.image_vert), .vertex),
        };
        errdefer {
            inline for (.{
                &modules.bg_color_frag,
                &modules.bg_image_frag,
                &modules.bg_image_vert,
                &modules.cell_bg_frag,
                &modules.cell_text_frag,
                &modules.cell_text_vert,
                &modules.full_screen_vert,
                &modules.image_frag,
                &modules.image_vert,
            }) |m_ptr| {
                if (m_ptr.handle != null) m_ptr.deinit();
            }
        }

        // Descriptor pool. Each pipeline allocates one set per
        // resource bucket it uses (UBO / sampler / storage); the
        // pool sized from the actual built-in pipeline footprint
        // PLUS two sets per post (custom-shader) pipeline (UBO at
        // set 0 binding 1, iChannel0 sampler at set 1 binding 0).
        //
        // Built-in footprint: 13 sets total
        //   bg_color   : 1 UBO
        //   cell_bg    : 1 UBO + 1 storage
        //   cell_text  : 1 UBO + 1 sampler + 1 storage
        //   image      : 1 UBO + 1 sampler
        //   bg_image   : 1 UBO + 1 sampler
        //   = 5 UBO + 3 sampler + 2 storage = 10 sets
        // Plus a handful of placeholder DSLs / empty sets handed
        // back to `Pipeline.init` for unused slots; round to 16 for
        // headroom.
        //
        // Per post-shader: 2 sets (1 UBO + 1 sampler).
        const builtin_sets: u32 = 16;
        const builtin_ubos: u32 = 8;
        const builtin_samplers: u32 = 8;
        const builtin_storage: u32 = 4;
        const post_count: u32 = @intCast(post_shaders.len);
        const pool_max_sets = builtin_sets + 2 * post_count;
        const pool_ubos = builtin_ubos + post_count;
        const pool_samplers = builtin_samplers + post_count;
        var pool = try DescriptorPool.init(.{
            .device = device,
            .max_sets = pool_max_sets,
            .uniform_buffers = pool_ubos,
            .combined_image_samplers = pool_samplers,
            .storage_buffers = builtin_storage,
        });
        errdefer pool.deinit();

        // ---- 0-binding placeholder DSL ---------------------------
        //
        // Used to fill `pSetLayouts[i]` for set indices a pipeline
        // doesn't actually use (e.g. cell_bg uses set 0 and set 2,
        // so set 1 needs a non-null placeholder).
        const empty_dsl_info: vk.VkDescriptorSetLayoutCreateInfo = .{
            .sType = vk.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
            .pNext = null,
            .flags = 0,
            .bindingCount = 0,
            .pBindings = null,
        };
        var empty_dsl: vk.VkDescriptorSetLayout = undefined;
        if (device.dispatch.createDescriptorSetLayout(
            device.device,
            &empty_dsl_info,
            null,
            &empty_dsl,
        ) != vk.VK_SUCCESS) {
            return error.VulkanFailed;
        }

        // Layout tracker — captures every DSL we create so deinit
        // can tear them down without per-pipeline bookkeeping.
        var set_layouts: [16]vk.VkDescriptorSetLayout = [_]vk.VkDescriptorSetLayout{null} ** 16;
        var set_layouts_len: usize = 0;
        set_layouts[set_layouts_len] = empty_dsl;
        set_layouts_len += 1;
        errdefer {
            for (set_layouts[0..set_layouts_len]) |dsl| {
                if (dsl != null) device.dispatch.destroyDescriptorSetLayout(
                    device.device,
                    dsl,
                    null,
                );
            }
        }

        // Helper: track + return.
        const Tracker = struct {
            arr: *[16]vk.VkDescriptorSetLayout,
            len: *usize,
            fn track(t: @This(), dsl: vk.VkDescriptorSetLayout) void {
                t.arr.*[t.len.*] = dsl;
                t.len.* += 1;
            }
        };
        const tracker = Tracker{ .arr = &set_layouts, .len = &set_layouts_len };

        // ---- bg_color pipeline -----------------------------------
        //
        // Full-screen fragment shader that reads the bg color out of
        // the Globals UBO. The vertex shader (`full_screen.v.glsl`)
        // synthesizes a covering triangle from `gl_VertexIndex`, so
        // there's no vertex input.
        //
        // After `vulkanizeGlsl`, the Globals UBO lives at set=0,
        // binding=1. bg_color doesn't use samplers or storage
        // buffers, so the pipeline needs only one descriptor set
        // layout.
        const bg_color_ubo_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(bg_color_ubo_dsl);
        const bg_color_pipeline = try Pipeline.init(.{
            .device = device,
            .descriptor_pool = &pool,
            .vertex_module = modules.full_screen_vert.handle,
            .fragment_module = modules.bg_color_frag.handle,
            .vertex_input = null,
            .descriptor_set_layouts = &.{bg_color_ubo_dsl},
            .empty_set_layout = empty_dsl,
            .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
            .blending_enabled = false,
            .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        });
        errdefer bg_color_pipeline.deinit();

        // ---- cell_bg pipeline ------------------------------------
        //
        // Full-screen fragment shader that reads per-cell background
        // colors out of `bg_cells` (storage buffer) and the Globals
        // UBO. After `vulkanizeGlsl`:
        //
        //   set 0 binding 1  Globals UBO  (fragment stage)
        //   set 2 binding 1  bg_cells storage buffer (fragment stage)
        //
        // Set 1 is unused — the empty DSL fills the slot so the
        // pipeline layout's `pSetLayouts` is contiguous.
        const cell_bg_ubo_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(cell_bg_ubo_dsl);
        const cell_bg_storage_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(cell_bg_storage_dsl);
        const cell_bg_pipeline = try Pipeline.init(.{
            .device = device,
            .descriptor_pool = &pool,
            .vertex_module = modules.full_screen_vert.handle,
            .fragment_module = modules.cell_bg_frag.handle,
            .vertex_input = null,
            .descriptor_set_layouts = &.{ cell_bg_ubo_dsl, null, cell_bg_storage_dsl },
            .empty_set_layout = empty_dsl,
            .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
            .blending_enabled = true,
            .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        });
        errdefer cell_bg_pipeline.deinit();

        // ---- cell_text pipeline ----------------------------------
        //
        // The big one: actual glyph rendering. After `vulkanizeGlsl`:
        //
        //   set 0 binding 1  Globals UBO  (both stages)
        //   set 1 binding 0  atlas_grayscale combined sampler (frag)
        //   set 1 binding 1  atlas_color combined sampler (frag)
        //   set 2 binding 1  bg_cells storage buffer (vertex stage)
        //
        // Vertex input is the per-instance `CellText` struct from
        // this file (above), one instance per visible glyph. The
        // vertex shader is a 4-vertex triangle strip producing the
        // glyph quad.
        //
        // Sampler: an unnormalized-coordinate sampler shared between
        // the two atlases. `vulkanizeGlsl` rewrote `sampler2DRect` to
        // `sampler2D`; the matching VkSampler uses
        // unnormalizedCoordinates so `texture(s, pixel_xy)` keeps the
        // OpenGL `sampler2DRect` semantics the shaders were written
        // against.
        const atlas_sampler = try Sampler.init(.{
            .device = device,
            .min_filter = .nearest,
            .mag_filter = .nearest,
            .wrap_s = .clamp_to_edge,
            .wrap_t = .clamp_to_edge,
            .unnormalized_coordinates = true,
        });
        errdefer atlas_sampler.deinit();

        const cell_text_ubo_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            vk.VK_SHADER_STAGE_VERTEX_BIT | vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(cell_text_ubo_dsl);

        // Set 1: two combined-image-sampler bindings (atlas_grayscale
        // at binding 0, atlas_color at binding 1). Both fragment stage.
        const cell_text_sampler_bindings = [_]vk.VkDescriptorSetLayoutBinding{
            .{
                .binding = 0,
                .descriptorType = vk.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                .descriptorCount = 1,
                .stageFlags = vk.VK_SHADER_STAGE_FRAGMENT_BIT,
                .pImmutableSamplers = null,
            },
            .{
                .binding = 1,
                .descriptorType = vk.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                .descriptorCount = 1,
                .stageFlags = vk.VK_SHADER_STAGE_FRAGMENT_BIT,
                .pImmutableSamplers = null,
            },
        };
        const cell_text_sampler_dsl_info: vk.VkDescriptorSetLayoutCreateInfo = .{
            .sType = vk.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
            .pNext = null,
            .flags = 0,
            .bindingCount = cell_text_sampler_bindings.len,
            .pBindings = &cell_text_sampler_bindings,
        };
        var cell_text_sampler_dsl: vk.VkDescriptorSetLayout = undefined;
        if (device.dispatch.createDescriptorSetLayout(
            device.device,
            &cell_text_sampler_dsl_info,
            null,
            &cell_text_sampler_dsl,
        ) != vk.VK_SUCCESS) {
            return error.VulkanFailed;
        }
        tracker.track(cell_text_sampler_dsl);

        const cell_text_storage_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            vk.VK_SHADER_STAGE_VERTEX_BIT,
        );
        tracker.track(cell_text_storage_dsl);

        // Vertex input. The 7 attributes match the fields of
        // `CellText` declared above (size 32 bytes). Each field's
        // VkFormat is picked to match the GLSL `in` type:
        //   glyph_pos uvec2  → R32G32_UINT     (offset 0)
        //   glyph_size uvec2 → R32G32_UINT     (offset 8)
        //   bearings ivec2   → R16G16_SINT     (offset 16)
        //   grid_pos uvec2   → R16G16_UINT     (offset 20)
        //   color uvec4      → R8G8B8A8_UINT   (offset 24)
        //   atlas uint       → R8_UINT         (offset 28)
        //   glyph_bools uint → R8_UINT         (offset 29)
        const cell_text_attrs = [_]vk.VkVertexInputAttributeDescription{
            .{ .location = 0, .binding = 0, .format = vk.VK_FORMAT_R32G32_UINT, .offset = 0 },
            .{ .location = 1, .binding = 0, .format = vk.VK_FORMAT_R32G32_UINT, .offset = 8 },
            .{ .location = 2, .binding = 0, .format = vk.VK_FORMAT_R16G16_SINT, .offset = 16 },
            .{ .location = 3, .binding = 0, .format = vk.VK_FORMAT_R16G16_UINT, .offset = 20 },
            .{ .location = 4, .binding = 0, .format = vk.VK_FORMAT_R8G8B8A8_UINT, .offset = 24 },
            .{ .location = 5, .binding = 0, .format = vk.VK_FORMAT_R8_UINT, .offset = 28 },
            .{ .location = 6, .binding = 0, .format = vk.VK_FORMAT_R8_UINT, .offset = 29 },
        };
        const cell_text_pipeline = try Pipeline.init(.{
            .device = device,
            .descriptor_pool = &pool,
            .vertex_module = modules.cell_text_vert.handle,
            .fragment_module = modules.cell_text_frag.handle,
            .vertex_input = .{
                .stride = @sizeOf(CellText),
                .step_fn = .per_instance,
                .attributes = &cell_text_attrs,
            },
            .descriptor_set_layouts = &.{ cell_text_ubo_dsl, cell_text_sampler_dsl, cell_text_storage_dsl },
            .empty_set_layout = empty_dsl,
            .sampler = atlas_sampler.sampler,
            .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
            .blending_enabled = true,
            .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
        });
        errdefer cell_text_pipeline.deinit();

        // ---- image pipeline (kitty graphics, overlay) ------------
        //
        // Per-instance fullscreen quad (triangle-strip, 4 verts) that
        // draws ONE image rectangle into the grid. The renderer's
        // `image.zig:draw` records one Step per visible placement,
        // each with its own VkBuffer (the per-instance `Image`
        // struct) and texture.
        //
        // Bindings after `vulkanizeGlsl`:
        //   set 0 binding 1  Globals UBO (vert+frag)
        //   set 1 binding 0  combined image sampler (the kitty image
        //                    texture, normalized sampling)
        //
        // Per-draw VkBuffer allocation is fine here because
        // `Buffer.deinit` returns its allocation to `Vulkan.buffer_pool`
        // instead of destroying it — same 48-byte buffer flows through
        // 100s of placements per frame without driver allocation
        // pressure. The pipeline's pre-allocated descriptor set IS
        // aliased across image draws (all `image` Steps share it),
        // but the common case (fastfetch's logo, a single image
        // replicated across grid cells) reuses ONE texture so the
        // alias resolves correctly. Multi-texture placements in a
        // single frame would need a per-draw descriptor set
        // allocator; that's a follow-up.
        const image_ubo_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            vk.VK_SHADER_STAGE_VERTEX_BIT | vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(image_ubo_dsl);
        const image_sampler_dsl = try createSingleBindingDsl(
            device,
            0,
            vk.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
            vk.VK_SHADER_STAGE_VERTEX_BIT | vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(image_sampler_dsl);
        const image_attrs = [_]vk.VkVertexInputAttributeDescription{
            .{ .location = 0, .binding = 0, .format = vk.VK_FORMAT_R32G32_SFLOAT, .offset = @offsetOf(Image, "grid_pos") },
            .{ .location = 1, .binding = 0, .format = vk.VK_FORMAT_R32G32_SFLOAT, .offset = @offsetOf(Image, "cell_offset") },
            .{ .location = 2, .binding = 0, .format = vk.VK_FORMAT_R32G32B32A32_SFLOAT, .offset = @offsetOf(Image, "source_rect") },
            .{ .location = 3, .binding = 0, .format = vk.VK_FORMAT_R32G32_SFLOAT, .offset = @offsetOf(Image, "dest_size") },
        };
        // Normalized linear sampler shared by image + bg_image,
        // separate from `atlas_sampler` (which is unnormalized for
        // cell_text's pixel-coord glyph atlas).
        const image_sampler = try Sampler.init(.{
            .device = device,
            .min_filter = .linear,
            .mag_filter = .linear,
            .wrap_s = .clamp_to_edge,
            .wrap_t = .clamp_to_edge,
        });
        errdefer image_sampler.deinit();

        const image_pipeline = try Pipeline.init(.{
            .device = device,
            .descriptor_pool = &pool,
            .vertex_module = modules.image_vert.handle,
            .fragment_module = modules.image_frag.handle,
            .vertex_input = .{
                .stride = @sizeOf(Image),
                .step_fn = .per_instance,
                .attributes = &image_attrs,
            },
            .descriptor_set_layouts = &.{ image_ubo_dsl, image_sampler_dsl },
            .empty_set_layout = empty_dsl,
            .sampler = image_sampler.sampler,
            .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
            .blending_enabled = true,
            .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
        });
        errdefer image_pipeline.deinit();

        // ---- bg_image pipeline -----------------------------------
        const bg_image_ubo_dsl = try createSingleBindingDsl(
            device,
            1,
            vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            vk.VK_SHADER_STAGE_VERTEX_BIT | vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(bg_image_ubo_dsl);
        const bg_image_sampler_dsl = try createSingleBindingDsl(
            device,
            0,
            vk.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
            vk.VK_SHADER_STAGE_VERTEX_BIT | vk.VK_SHADER_STAGE_FRAGMENT_BIT,
        );
        tracker.track(bg_image_sampler_dsl);
        const bg_image_attrs = [_]vk.VkVertexInputAttributeDescription{
            .{ .location = 0, .binding = 0, .format = vk.VK_FORMAT_R32_SFLOAT, .offset = @offsetOf(BgImage, "opacity") },
            .{ .location = 1, .binding = 0, .format = vk.VK_FORMAT_R8_UINT, .offset = @offsetOf(BgImage, "info") },
        };
        const bg_image_pipeline = try Pipeline.init(.{
            .device = device,
            .descriptor_pool = &pool,
            .vertex_module = modules.bg_image_vert.handle,
            .fragment_module = modules.bg_image_frag.handle,
            .vertex_input = .{
                .stride = @sizeOf(BgImage),
                .step_fn = .per_instance,
                .attributes = &bg_image_attrs,
            },
            .descriptor_set_layouts = &.{ bg_image_ubo_dsl, bg_image_sampler_dsl },
            .empty_set_layout = empty_dsl,
            .sampler = image_sampler.sampler,
            .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
            .blending_enabled = true,
            .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        });
        errdefer bg_image_pipeline.deinit();

        var pipelines: PipelineCollection = .{};
        pipelines.bg_color = bg_color_pipeline;
        pipelines.cell_bg = cell_bg_pipeline;
        pipelines.cell_text = cell_text_pipeline;
        pipelines.image = image_pipeline;
        pipelines.bg_image = bg_image_pipeline;

        // ---- post (custom shader) pipelines ----------------------
        //
        // One pipeline per user shader source in `post_shaders`. Each
        // pipeline is the same shape:
        //
        //   set 0 binding 1  Globals UBO (shadertoy uniforms)
        //   set 1 binding 0  iChannel0 combined image sampler
        //                    (the prior pass's back_texture +
        //                    `state.sampler` from CustomShaderState)
        //
        // The vertex shader is the same `full_screen_vert` triangle
        // generator we use for bg_color; the user-supplied source IS
        // the fragment shader (run through `vulkanizeGlsl` and the
        // glslang shim — same path the built-in shaders take).
        // Color format matches `textureOptions()` and `initTarget`
        // (BGRA SRGB) since post passes write to either a
        // back_texture or `frame.target` and both use that format.
        //
        // Shadertoy shaders sample with normalized coordinates so the
        // post pipeline's sampler is the normalized `state.sampler`,
        // not the atlas sampler.
        var post_pipelines: []Pipeline = &.{};
        var post_modules: []Module = &.{};
        if (post_shaders.len > 0) {
            post_pipelines = try alloc.alloc(Pipeline, post_shaders.len);
            errdefer alloc.free(post_pipelines);
            post_modules = try alloc.alloc(Module, post_shaders.len);
            errdefer alloc.free(post_modules);

            // Init counters so partial failures deinit exactly what
            // was built. We track modules and pipelines separately
            // because the inner loop creates a module first, then
            // tries to build a pipeline against it — if Pipeline.init
            // fails after Module.initFromSpirv succeeded, the module
            // is populated but the pipeline isn't.
            var modules_built: usize = 0;
            var pipelines_built: usize = 0;
            errdefer {
                for (post_pipelines[0..pipelines_built]) |p| p.deinit();
                for (post_modules[0..modules_built]) |m| m.deinit();
            }

            // Shared descriptor set layouts across post pipelines.
            // Tracked in `set_layouts` so deinit destroys once.
            const post_ubo_dsl = try createSingleBindingDsl(
                device,
                1,
                vk.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
                vk.VK_SHADER_STAGE_FRAGMENT_BIT,
            );
            tracker.track(post_ubo_dsl);
            const post_sampler_dsl = try createSingleBindingDsl(
                device,
                0,
                vk.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                vk.VK_SHADER_STAGE_FRAGMENT_BIT,
            );
            tracker.track(post_sampler_dsl);

            for (post_shaders, 0..) |spv_bytes, i| {
                // Reinterpret the binary as the 32-bit word slice
                // Vulkan's VkShaderModuleCreateInfo wants. The
                // allocation is over-aligned to `u32` in shadertoy.zig
                // so this cast is safe.
                if (spv_bytes.len % 4 != 0) {
                    log.err("custom shader SPIR-V size {} not a multiple of 4", .{spv_bytes.len});
                    return error.VulkanFailed;
                }
                const spv_words: []const u32 = std.mem.bytesAsSlice(u32, @as([]align(@alignOf(u32)) const u8, @alignCast(spv_bytes)));
                post_modules[i] = try Module.initFromSpirv(device, spv_words, .fragment);
                modules_built = i + 1;
                post_pipelines[i] = try Pipeline.init(.{
                    .device = device,
                    .descriptor_pool = &pool,
                    .vertex_module = modules.full_screen_vert.handle,
                    .fragment_module = post_modules[i].handle,
                    .vertex_input = null,
                    .descriptor_set_layouts = &.{ post_ubo_dsl, post_sampler_dsl },
                    .empty_set_layout = empty_dsl,
                    .color_format = vk.VK_FORMAT_B8G8R8A8_SRGB,
                    .blending_enabled = false,
                    .topology = vk.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
                });
                pipelines_built = i + 1;
            }
        }

        return .{
            .device = device,
            .pipelines = pipelines,
            .post_pipelines = post_pipelines,
            .post_modules = post_modules,
            .modules = modules,
            .descriptor_pool = pool,
            .set_layouts = set_layouts,
            .set_layouts_len = set_layouts_len,
            .empty_set_layout = empty_dsl,
            .atlas_sampler = atlas_sampler,
            .image_sampler = image_sampler,
        };
    }

    /// Construct a single-binding `VkDescriptorSetLayout`. The vast
    /// majority of our per-set layouts have exactly one binding
    /// (Globals UBO, bg_cells SSBO, individual sampler) so a helper
    /// keeps the call sites short.
    fn createSingleBindingDsl(
        device: *const Device,
        binding: u32,
        descriptor_type: vk.VkDescriptorType,
        stage_flags: vk.VkShaderStageFlags,
    ) !vk.VkDescriptorSetLayout {
        const bindings = [_]vk.VkDescriptorSetLayoutBinding{.{
            .binding = binding,
            .descriptorType = descriptor_type,
            .descriptorCount = 1,
            .stageFlags = stage_flags,
            .pImmutableSamplers = null,
        }};
        const info: vk.VkDescriptorSetLayoutCreateInfo = .{
            .sType = vk.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
            .pNext = null,
            .flags = 0,
            .bindingCount = bindings.len,
            .pBindings = &bindings,
        };
        var dsl: vk.VkDescriptorSetLayout = undefined;
        if (device.dispatch.createDescriptorSetLayout(
            device.device,
            &info,
            null,
            &dsl,
        ) != vk.VK_SUCCESS) {
            return error.VulkanFailed;
        }
        return dsl;
    }

    pub fn deinit(self: *Shaders, alloc: Allocator) void {
        if (self.defunct) return;
        self.defunct = true;

        // Pipelines first — each holds a VkPipelineLayout that
        // references the descriptor set layouts we're about to
        // destroy. Skip default-null sentinel slots.
        inline for (.{
            &self.pipelines.bg_color,
            &self.pipelines.bg_image,
            &self.pipelines.cell_bg,
            &self.pipelines.cell_text,
            &self.pipelines.image,
        }) |p_ptr| {
            if (p_ptr.pipeline != null) p_ptr.deinit();
        }

        // Post (custom shader) pipelines + their fragment modules.
        // Same teardown order as the built-in pipelines/modules:
        // pipeline first (holds VkPipelineLayout), then shader module.
        for (self.post_pipelines) |p| p.deinit();
        for (self.post_modules) |m| m.deinit();
        // The slices were allocated from the same allocator the
        // caller hands to deinit (the renderer's `self.alloc`).
        // Use it directly — the previous `post_alloc` field was
        // an extra source of truth for the same value.
        if (self.post_pipelines.len > 0) alloc.free(self.post_pipelines);
        if (self.post_modules.len > 0) alloc.free(self.post_modules);

        // Atlas sampler held by `Shaders` for the cell_text pipeline's
        // texture bindings.
        if (self.atlas_sampler) |samp| samp.deinit();
        if (self.image_sampler) |samp| samp.deinit();

        // Descriptor pool reclaims every set allocated from it
        // (including the per-pipeline sets); the standalone layouts
        // are tracked separately in `set_layouts`.
        if (self.descriptor_pool) |*p| p.deinit();

        // Destroy every descriptor set layout we created. The empty
        // placeholder is one of the entries.
        const dev = self.device;
        for (self.set_layouts[0..self.set_layouts_len]) |dsl| {
            if (dsl != null) dev.dispatch.destroyDescriptorSetLayout(
                dev.device,
                dsl,
                null,
            );
        }

        // Destroy every compiled module. Modules whose handle is
        // null skip destruction — vkDestroy* is null-safe per the
        // Vulkan spec but we check explicitly so we don't pass null
        // through the dispatch.
        inline for (.{
            &self.modules.bg_color_frag,
            &self.modules.bg_image_frag,
            &self.modules.bg_image_vert,
            &self.modules.cell_bg_frag,
            &self.modules.cell_text_frag,
            &self.modules.cell_text_vert,
            &self.modules.full_screen_vert,
            &self.modules.image_frag,
            &self.modules.image_vert,
        }) |m_ptr| {
            if (m_ptr.handle != null) m_ptr.deinit();
        }
    }
};

test {
    std.testing.refAllDecls(@This());
}

test "vulkanizeGlsl: gl_VertexID and gl_InstanceID rename" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\void main() {
        \\    int vid = gl_VertexID;
        \\    int iid = gl_InstanceID;
        \\    // gl_VertexID_x stays unchanged (not whole-word)
        \\    int x = my_gl_VertexID_x;
        \\}
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "gl_VertexIndex") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "gl_InstanceIndex") != null);
    // Whole-word: gl_VertexID itself must be gone.
    try std.testing.expect(std.mem.indexOf(u8, out, " gl_VertexID;") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, " gl_InstanceID;") == null);
    // But my_gl_VertexID_x is a different identifier — must survive intact.
    try std.testing.expect(std.mem.indexOf(u8, out, "my_gl_VertexID_x") != null);
}

test "vulkanizeGlsl: sampler2DRect to sampler2D" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(binding = 0) uniform sampler2DRect atlas_grayscale;
        \\layout(binding = 1) uniform sampler2DRect atlas_color;
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "sampler2DRect") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "sampler2D atlas_grayscale") != null);
}

test "vulkanizeGlsl: UBO block gets set=0" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(binding = 1, std140) uniform Globals {
        \\    float x;
        \\};
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "layout(set = 0, binding = 1, std140) uniform Globals") != null);
}

test "vulkanizeGlsl: sampler gets set=1" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(binding = 0) uniform sampler2D image;
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "layout(set = 1, binding = 0) uniform sampler2D image") != null);
}

test "vulkanizeGlsl: rewritten sampler2DRect still gets set=1" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(binding = 1) uniform sampler2DRect atlas;
    );
    defer std.testing.allocator.free(out);
    // After pass 1, type is sampler2D; pass 2 sees sampler*, sets set=1.
    try std.testing.expect(std.mem.indexOf(u8, out, "layout(set = 1, binding = 1) uniform sampler2D atlas") != null);
}

test "vulkanizeGlsl: storage buffer gets set=2" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(binding = 1, std430) readonly buffer bg_cells {
        \\    uint cells[];
        \\};
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "layout(set = 2, binding = 1, std430) readonly buffer bg_cells") != null);
}

test "vulkanizeGlsl: location-only layout passes through" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\layout(location = 0) in vec2 in_grid_pos;
        \\layout(location = 0) out vec4 out_FragColor;
    );
    defer std.testing.allocator.free(out);
    // No `set = ` insertion because there's no `binding = `.
    try std.testing.expect(std.mem.indexOf(u8, out, "set =") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "layout(location = 0) in vec2 in_grid_pos") != null);
}

test "vulkanizeGlsl: texture() becomes textureLod(...,0.0)" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\float a = texture(atlas_grayscale, in_data.tex_coord).r;
        \\vec4 c = texture(atlas_color, vec2(1.0, 2.0));
    );
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "textureLod(atlas_grayscale, in_data.tex_coord, 0.0)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "textureLod(atlas_color, vec2(1.0, 2.0), 0.0)") != null);
    // No naked `texture(` remains.
    try std.testing.expect(std.mem.indexOf(u8, out, " texture(") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "=texture(") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "= texture(") == null);
}

test "vulkanizeGlsl: textureLod is left alone" {
    const out = try vulkanizeGlsl(std.testing.allocator,
        \\float a = textureLod(atlas, uv, 1.0).r;
    );
    defer std.testing.allocator.free(out);
    // No double-injection.
    try std.testing.expect(std.mem.indexOf(u8, out, "textureLod(atlas, uv, 1.0)") != null);
}

test "vulkanizeGlsl: layout with pre-existing set qualifier is unchanged" {
    const src =
        \\layout(set = 3, binding = 0) uniform sampler2D image;
    ;
    const out = try vulkanizeGlsl(std.testing.allocator, src);
    defer std.testing.allocator.free(out);
    // We never collapse a user-specified set, even if it disagrees
    // with our resource-type heuristic — better to surface a glslang
    // error than to silently rewrite.
    try std.testing.expect(std.mem.indexOf(u8, out, "set = 3") != null);
}

// ---- glslang integration tests --------------------------------------
//
// `vulkanizeGlsl` unit tests above exercise the textual rewrite in
// isolation. The integration tests below feed the rewriter's output
// through `glslang.vk.compileToSpv` and assert the result is a valid
// SPIR-V binary. That covers the seam where a syntactically-fine
// rewrite still produces something glslang rejects (e.g. a `set = N`
// on a declaration glslang's `--auto-map-bindings` is also trying
// to assign).

fn compileToSpv(
    alloc: std.mem.Allocator,
    src: [:0]const u8,
    stage: Stage,
) ![]const u32 {
    glslang.testing.ensureInit() catch return error.GlslangFailed;
    const translated = try vulkanizeGlsl(alloc, src);
    defer alloc.free(translated);
    return try glslang.vk.compileToSpv(alloc, translated, stage.vkBindingStage());
}

test "glslang integration: built-in bg_color fragment compiles" {
    const alloc = std.testing.allocator;
    const spv = try compileToSpv(alloc, source.bg_color_frag, .fragment);
    defer alloc.free(spv);
    // SPIR-V magic word — first 4 bytes are 0x07230203.
    try std.testing.expect(spv.len > 0);
    try std.testing.expectEqual(@as(u32, 0x07230203), spv[0]);
}

test "glslang integration: built-in cell_text vertex compiles" {
    const alloc = std.testing.allocator;
    const spv = try compileToSpv(alloc, source.cell_text_vert, .vertex);
    defer alloc.free(spv);
    try std.testing.expect(spv.len > 0);
    try std.testing.expectEqual(@as(u32, 0x07230203), spv[0]);
}

test "glslang integration: cell_bg fragment compiles (non-contiguous sets)" {
    // cell_bg uses set 0 (UBO) and set 2 (storage) — set 1 is the
    // empty placeholder DSL. The rewriter has to produce something
    // glslang can compile despite the gap; this test catches a
    // regression where the rewrite emits set=1 for the storage
    // buffer and breaks the pipeline layout assumption.
    const alloc = std.testing.allocator;
    const spv = try compileToSpv(alloc, source.cell_bg_frag, .fragment);
    defer alloc.free(spv);
    try std.testing.expect(spv.len > 0);
    try std.testing.expectEqual(@as(u32, 0x07230203), spv[0]);
}

test "glslang integration: full_screen vertex compiles" {
    const alloc = std.testing.allocator;
    const spv = try compileToSpv(alloc, source.full_screen_vert, .vertex);
    defer alloc.free(spv);
    try std.testing.expect(spv.len > 0);
    try std.testing.expectEqual(@as(u32, 0x07230203), spv[0]);
}
