name: Request Review

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  PY_COLORS: 1

jobs:
  review:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@f23fbf3b586540a96f4f5849a5e04c7e56e1e804 # v1.2.0
        with:
          path: |
            /nix
            /zig

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ghostty
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Request Localization Review
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REVIEW_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: nix develop -c uv run .github/scripts/request_review.py
